services:
  api:
    build: .
    ports:
      - 8000:8000
    image: openai-api
    volumes:
      - ~/.aws:/root/.aws
      - /home/ec2-user/working-directory/ai-for-u-backend/src/api/lambda:/app
    environment:
      DEV_PORT: 8000
      ENDPOINT: "http://localhost:8000"
      DOMAIN: "localhost"
      OPENAI_ROUTE_PREFIX: "openai"
      OPENAI_LAMBDA_ID: "openai_lambda"
      EXTERNAL_API_SECRET_NAME: "openai/apikey"
      API_ENDPOINT_SECRET_NAME: "openai_org_id"
      API_KEY_SECRET_KEY_NAME: "openai_api_key"
      FRONTEND_CORS_URL: "http://localhost:8000"
      AWS_REGION: "us-east-1"